services:
    auth.provider.remoteuser:
        class: cheshirekow\remoteuserauth\provider
        parent: auth.provider.db
        shared: false
        calls:
            - [set_language, ['@language']]
        tags:
            - { name: auth.provider }
